# Generated by Django 4.1 on 2023-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='local_govt',
            new_name='state',
        ),
        migrations.AddField(
            model_name='vendor',
            name='lga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
