# Generated by Django 4.1 on 2023-03-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_local_govt_vendor_state_vendor_lga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
