# Generated by Django 4.1 on 2023-03-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
