# Generated by Django 4.1 on 2023-03-29 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(choices=[('Your order has been taken and is being processed.', 'Your order has been taken and is being processed.'), ('Your order has been delivered!', 'Your order has been delivered!'), ('You have paid 500 registration fee.', 'You have paid 500 registration fee.'), ('Your product upload was not approved. Please contact the company surpport line.', 'Your product upload was not approved. Please contact the company surpport line.'), ('Your product upload has been approved!', 'Your product upload has been approved!')], max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
