# Generated by Django 4.1 on 2023-03-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('supermarket', 'supermarket'), ('shoe', 'shoe'), ('bag', 'bag'), ('food', 'food'), ('watch', 'watch'), ('eletronic', 'eletronic'), ('phone', 'phone')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vendor')),
            ],
        ),
    ]
