# Generated by Django 4.1 on 2023-03-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
