# Generated by Django 4.1 on 2023-03-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_status_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sales',
            field=models.IntegerField(null=True),
        ),
    ]
