# Generated by Django 4.1 on 2023-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='statics/img/bg2.png', upload_to=''),
        ),
    ]
