# Generated by Django 4.1 on 2023-03-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_vendor_image'),
        ('products', '0021_alter_cart_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='user.vendor'),
        ),
    ]
